version: '3.1'
services:
  listener:
    build: https://github.com/vives-projectwerk2-2019/TTN-Listener.git
    env_file:
      - docker-vars-listener.env
    depends_on:
      - broker
    networks:
      - public
  broker:
    build: https://github.com/vives-projectwerk2-2019/bug-broker.git
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - public
      - api
  api:
    build: https://github.com/vives-projectwerk2-2019/bug-api.git
    env_file:
      - docker-vars-api.env
    depends_on:
      - broker
    networks:
      - api
  kiosk:
    build: https://github.com/vives-projectwerk2-2019/bug-kiosk.git
    ports:
      - 80:8000
      - 443:443
    env_file:
      - docker-vars-kiosk.env
    depends_on:
      - db
    networks:
      - public
      - db
      - api
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: randomized
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bug
    env_file:
      - docker-vars-mariadb.env
    networks:
      - db
networks:
  public:
  db:
  api:
