version: '3.1'
services:
  listener:
    image: buguniversalgamecontroller/ttn-listener:latest
    build: https://github.com/vives-projectwerk2-2019/TTN-Listener.git
    env_file:
      - docker-vars-listener.env
    depends_on:
      - broker
    networks:
      - public
  broker:
    image: buguniversalgamecontroller/broker:latest
    build: https://github.com/vives-projectwerk2-2019/bug-broker.git
    ports:
      - 9001
    networks:
      - public
      - api
  api:
    image: buguniversalgamecontroller/api:latest
    build: https://github.com/vives-projectwerk2-2019/bug-api.git
    env_file:
      - docker-vars-api.env
    depends_on:
      - broker
    networks:
      - api
  kiosk:
    image: buguniversalgamecontroller/kiosk:latest
    build: https://github.com/vives-projectwerk2-2019/bug-kiosk.git
    ports:
      - 8000
    env_file:
      - docker-vars-kiosk.env
    depends_on:
      - db
    networks:
      - public
      - db
      - api
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: randomized
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bug
    env_file:
      - docker-vars-mariadb.env
    networks:
      - db
  game:
    image: buguniversalgamecontroller/game:latest
    build: https://github.com/vives-projectwerk2-2019/game-frontend.git
    ports:
      - 80 
    networks:
      - public
  game-server:
    image: buguniversalgamecontroller/game-server:latest
    build: https://github.com/vives-projectwerk2-2019/game-server.git
    ports:
      - 9001
    networks:
      - public
networks:
  public:
  db:
  api:
