version: '3.1'
services:
  node:
    build: https://github.com/vives-projectwerk2-2019/bug-api.git
    ports:
      - 8080:8080
    links:
      - mariadb:db
  mariadb:
    build: https://github.com/vives-projectwerk2-2019/bug-database.git
    ports:
      - 13306:13306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bug
      MYSQL_USER: api
      MYSQL_PASSWORD: api
  kiosk:
    build: https://github.com/vives-projectwerk2-2019/bug-kiosk.git
    ports:
      - 3000:3000
    links:
      - node:api
