version: '3.1'
services:
  broker:
    build: https://github.com/vives-projectwerk2-2019/bug-broker.git
    ports:
      - 1883:1883
  listener:
    build: https://github.com/vives-projectwerk2-2019/TTN-Listener.git
    env_file:
      - docker-vars-listener.env
    depends_on:
      - broker
  api:
    build: https://github.com/vives-projectwerk2-2019/bug-api.git
    env_file:
      - docker-vars-api.env
    depends_on:
      - broker
  db:
    build: https://github.com/vives-projectwerk2-2019/bug-database.git
    environment:
      MYSQL_ROOT_PASSWORD: randomized
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bug
    env_file:
      - docker-vars-mariadb.env
  kiosk:
    build: https://github.com/vives-projectwerk2-2019/bug-kiosk.git
    ports:
      - 3000:3000
    env_file:
      - docker-vars-kiosk.env
    depends_on:
      - db
