version: '3.1'
services:
  broker:
    build: https://github.com/vives-projectwerk2-2019/bug-broker.git
    ports:
      - 1883:1883
  db:
    build: https://github.com/vives-projectwerk2-2019/bug-database.git
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: bug
      MYSQL_USER: api
      MYSQL_PASSWORD: api
  kiosk:
    build: https://github.com/vives-projectwerk2-2019/bug-kiosk.git
    ports:
      - 3000:3000
  api:
    build: https://github.com/vives-projectwerk2-2019/bug-api.git
  listener:
    build: https://github.com/vives-projectwerk2-2019/TTN-Listener.git
